server:
  port: 10010

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        # 路由id，可以任意个数
        - id: user-service-route
          uri: http://127.0.0.1:9091
          # 路由断言：可以匹配映射路径(请求路径中包含/user的全部转到9091端口即user-service)
          predicates:
            - Path=/user/** # 注意Path是大写

eureka:
  client:
    service-url:
      defaulZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true