server:
  port: 9091

spring:
  application:
    name: user-service
  profiles:
    active: dev

  # 读取config
  cloud:
    config:
      fail-fast: true
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
      discovery:
        enabled: true
        service-id: cloud-config

# 注册到Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka